[theme]
base                   = "dark"
backgroundColor        = "#0d1117"
secondaryBackgroundColor = "#161b22"
textColor              = "#ffffff"
primaryColor           = "#388bfd"
font                   = "sans serif"
